all: bs bsI bsII bsMAC
bs: bs.cpp
	g++ bs.cpp -o bin/bs

bsI: bsI.cpp
	g++ bsI.cpp -o bin/bsI

bsII: bsII.cpp
	g++ bsII.cpp -o bin/bsII

bsMAC: bsMAC.cpp
	g++ bsMAC.cpp -o bin/bsMAC

clean:
	rm -f bin/bs bin/bsI bin/bsII bin/bsMAC
